spring:
  application:
    name: MicroServiceApp02

  boot:
    admin:
      client:
        url: http://localhost:8080/
server:
  port: 8485

management:
  endpoints:
    web:
      exposure:
        include: '*'

